### ISSUE TITLE
invalid dependencies keys

### ISSUE THREAD

**Issue by demosdemon** [platformsh/template-python2#9]
https://github.com/platformsh/template-python2/blob/8b20e6f5fa01aeec6e3a75476980721c623922ce/.platform.app.yaml#L14

the `python2`/`python3` distinction is only necessary on python3.4+ images. Python2 only supports Python2 so it's just `python`

**Comment by demosdemon** [comment]
revert https://github.com/platformsh/template-python2/commit/ac6aa05bd832655af9bd8ec9cf6af80ecb0fc298

**Comment by NickAnderegg** [comment]
This isn't accurate. All Python images support `python2` and `python3` with `python` pointing to the PEP 394 version.

Consider this build hook:

        python2 --version
        python3 --version
        python --version

        pip2 --version
        pip3 --version
        pip --version

And its output:

        Executing build hook...
          W: Python 2.7.16
          Python 3.4.2
          W: Python 2.7.16
          pip 8.1.2 from /opt/python/2.7/lib/python2.7/site-packages (python 2.7)
          pip 1.5.6 from /usr/lib/python3/dist-packages (python 3.4)
          pip 8.1.2 from /opt/python/2.7/lib/python2.7/site-packages (python 2.7)

**Comment by NickAnderegg** [comment]
@demosdemon See also: https://docs.platform.sh/configuration/app/build.html#python-dependencies
